# Generated by Django 4.1 on 2023-04-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_category_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="category",
        ),
    ]
