# Generated by Django 4.1 on 2023-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="closeStatus",
            field=models.BooleanField(default=False),
        ),
    ]
